#! /bin/bash

author () {
 echo -e "This is brought to you by \e[1mAlexandru Balan\e[21m under the"
 echo -e "\e[1mPearProject Team\e[21m"
 echo ""
 echo "Copyright 2021  PearProject All Rights Reserved"
}

help () {
 echo -e "\e[1;4mWelcome to the pearOS System Manager\e[24m"
 echo -e "Usage:  -v  --version      get this update's version"
 echo -e "        -c  --changelog    show the changelog"
 echo -e "        -a  --author       show the author of the pear Updates Manager"
 echo -e "        -k  --check        Check for updates immediatly"
 echo -e "        -r  --release      output the current pearOS Release\e[21m"
 echo -e "        -s  --stage         show the Build stage of the release"
 echo -e "        -h  --help         display this help screen"
}

release () {
 echo NiceC0re
}

stage () {
 echo Dev build
}

version () {
 echo 20210924
}

changelog () {
 echo -e " Initial NiceC0re release"
}

check () {
 echo -e "\e[1;4mChecking for updates, please wait...\e[0m"
 /usr/bin/update-mgr
}

error () {
 echo -e '\e[39m\e[41m! FATAL\e[0m:  \e[91mUnknown argument! Here is a help screen:' && help
}

case "$1" in
	--version) version ;;
	--changelog) changelog ;;
	--author) author ;;
	--check) check ;;
	--help) help ;;
	--release) release ;;
	--stage) stage ;;
	-v) version ;;
	-c) changelog ;;
	-a) author ;;
	-k) check ;;
	-h) help ;;
	-r) release ;;
	-s) stage ;;
	"") help ;;
	*) error
esac
