' Gambas module file

'Copyright (c) 2021 Alexandru Balan under PearProject All Rights Reserved
'This Software uses Pext-Installer - Copyrighted content from Axtlos, being part of PearProject
'Copyright (c) 2021 Axtlos under PearProject All Rights Reserved
'Any un-official modify of this software is strictly prohibited in any circumstance.
'For questions about this software, mail Alex at alex@pearos.xyz

Public new_update As Boolean                                      'making a boolean variable for later use
Public installed_version As String                                'making an "installed_version" string var. to store the installed update version
Public fetched_version As String                                  'making an "fetched version" string variable to store the NEW update version

Public Sub Main()                                                 'starting the main function
  Shell "rm -Rf /tmp/system-update && mkdir /tmp/system-update" Wait
  Shell "cd /tmp/system-update/ && wget https://updates.pearos.xyz/pearOS_updatefile_amd64.zip" Wait
  'fetch.download()                                                'starting Download function
  fetch.install()                                                 'installing the downloaded version
  check.local_version()                                           'checking the local version
  check.server_version()                                          'checking server update version
  If new_update = True Then                                       'if is there a new update, then
    notify.available                                              'the system is notified
  Endif                                                           'ending the if statemend
  If new_update = False Then                                      'if there is no update available
    Me.Close                                                      'program closes itself(resolving pr_not_closed bug)
  Endif                                                           'ending the IF statement
End                                                               'ending the main function of the programm
