' Gambas module file

'Copyright (c) 2021 Alexandru Balan under PearProject All Rights Reserved
'This Software uses Pext-Installer - Copyrighted content from Axtlos, being part of PearProject
'Copyright (c) 2021 Axtlos under PearProject All Rights Reserved
'Any un-official modify of this software is strictly prohibited in any circumstance.
'For questions about this software, mail Alex at alex@pearos.xyz

Public Sub available()                                                                                                                  'declaring the available() function
Shell "echo '\e[43m❖ SUCCESS:\e[0m \e[93mAn update is availale and is ready to be installed!\e[0m'"
Shell "kdialog --title 'Pear Update Manager' --passivepopup 'Updates are available. Open the System Update software to install them' 5" 'showing a KDE Notification if function called
Shell "cd /usr/share/pext-installer && python3 pext-installer"                                                                          'opening pexet-installer if function is called
End                                                                                                                                     'ending the available() function